influx:
  url: http://localhost:8000
  dbName: marketing_metrics
  retention: default
ga:
  cron: 0 * * * * *
  applicationName: Google Analytics Metrics Collector
  project_id:
  private_key_id:
  private_key:
  client_email:
  client_id:
  client_x509_cert_url:
  aqe-blog:
    viewId:
    hostName: blog.novatec-gmbh.de
    metrics:
      - ga:pageviews
      - ga:uniquePageviews
      - ga:sessions
      - ga:bounces
      - ga:bounceRate
      - ga:avgSessionDuration
      - ga:avgTimeOnPage
    dimensions:
      - ga:hostname
      - ga:pagePath
      - ga:pageTitle
    excluded-urls:
      - /
  aqe-homepage:
    viewId:
    hostName: novatec-gmbh.de