influx:
  url: http://localhost:8000
  dbName: marketing_metrics
  retention: default
ga:
  cron: 0 * * * * *
  applicationName: Google Analytics Metrics Collector
  project_id:
  private_key_id:
  private_key:
  client_email:
  client_id:
  client_x509_cert_url:
  shared-metrics:
    - ga:pageviews
    - ga:uniquePageviews
    - ga:sessions
    - ga:bounces
    - ga:bounceRate
    - ga:avgSessionDuration
    - ga:avgTimeOnPage
  shared-dimensions:
    - ga:hostname
    - ga:pagePath
    - ga:pageTitle
  aqe-blog:
    viewId: 0000
    hostName: blog.novatec-gmbh.de
    unique-metrics:
    #- ga:examplemetric
    unique-dimensions:
    #- ga:exampledimension
    excluded-urls:
      - /
  aqe-homepage:
    viewId: 0000
    hostName: novatec-gmbh.de
    unique-metrics:
    #- ga:examplemetric
    unique-dimensions:
    #- ga:exampledimension